apiVersion: v1
kind: Secret
metadata:
  name: ivp-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-host:5432/ivp"
  SPRING_DATASOURCE_USERNAME: "ivp"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
